<<<<<<< HEAD
<<<<<<< HEAD
component_depth: 10
=======
component_depth: 7
>>>>>>> parent of 24f410dce... Update .bettercodehub.yml
=======
component_depth: 8
>>>>>>> 19da469458aa5de7b010e66d91a28986838bf344
